

export default [
        {
        label:'账号管理',
        to:'',
        children:[
                        {
                label:'管理员账号管理',
                to:'/admin/admins',
            },
                        {
                label:'管理员账号添加',
                to:'/admin/adminsadd',
            },
                        {
                label:'注册用户管理',
                to:'/admin/yonghu',
            },
                        {
                label:'添加新用户',
                to:'/admin/yonghuadd',
            },
                        {
                label:'密码修改',
                to:'/admin/mod',
            },
                    ]
    },
        {
        label:'配送员管理',
        to:'',
        children:[
                        {
                label:'配送员添加',
                to:'/admin/peisongyuanadd',
            },
                        {
                label:'配送员查询',
                to:'/admin/peisongyuan',
            },
                        {
                label:'体温检测查询',
                to:'/admin/tiwenjiance',
            },
                    ]
    },
        {
        label:'商品分类管理',
        to:'',
        children:[
                        {
                label:'商品分类添加',
                to:'/admin/shangpinfenleiadd',
            },
                        {
                label:'商品分类查询',
                to:'/admin/shangpinfenlei',
            },
                    ]
    },
        {
        label:'商品信息管理',
        to:'',
        children:[
                        {
                label:'商品信息添加',
                to:'/admin/shangpinxinxiadd',
            },
                        {
                label:'商品信息查询',
                to:'/admin/shangpinxinxi',
            },
                    ]
    },
        {
        label:'订单信息管理',
        to:'',
        children:[
                        {
                label:'订单信息查询',
                to:'/admin/dingdanxinxi',
            },
                    ]
    },
        {
        label:'订单确认管理',
        to:'',
        children:[
                        {
                label:'订单确认查询',
                to:'/admin/dingdanqueren',
            },
                    ]
    },
        {
        label:'订单配送管理',
        to:'',
        children:[
                        {
                label:'订单配送查询',
                to:'/admin/dingdanpeisong',
            },
                    ]
    },
        {
        label:'订单签收管理',
        to:'',
        children:[
                        {
                label:'订单签收查询',
                to:'/admin/dingdanqianshou',
            },
                    ]
    },
        {
        label:'订单取消管理',
        to:'',
        children:[
                        {
                label:'订单取消查询',
                to:'/admin/dingdanquxiao',
            },
                    ]
    },
        {
        label:'新闻管理',
        to:'',
        children:[
                        {
                label:'分类添加',
                to:'/admin/xinwenfenleiadd',
            },
                        {
                label:'分类查询',
                to:'/admin/xinwenfenlei',
            },
                        {
                label:'新闻添加',
                to:'/admin/xinwenxinxiadd',
            },
                        {
                label:'新闻查询',
                to:'/admin/xinwenxinxi',
            },
                    ]
    },
        {
        label:'系统管理',
        to:'',
        children:[
                        {
                label:'友情链接添加',
                to:'/admin/youqinglianjieadd',
            },
                        {
                label:'友情链接查询',
                to:'/admin/youqinglianjie',
            },
                        {
                label:'轮播图添加',
                to:'/admin/lunbotuadd',
            },
                        {
                label:'轮播图查询',
                to:'/admin/lunbotu',
            },
                        {
                label:'留言管理',
                to:'/admin/liuyanban',
            },
                    ]
    },
    ]
