

export default [
        {
        label:'购物车信息管理',
        to:'',
        children:[
                        {
                label:'我的购物车查询',
                to:'/admin/gouwuche_goumairen',
            },
                    ]
    },
        {
        label:'订单信息管理',
        to:'',
        children:[
                        {
                label:'我的订单查询',
                to:'/admin/dingdanxinxi_xiadanren',
            },
                        {
                label:'订单配送查询',
                to:'/admin/dingdanpeisong_xiadanren',
            },
                        {
                label:'我的签收查询',
                to:'/admin/dingdanqianshou_pingjiaren',
            },
                        {
                label:'订单取消查询',
                to:'/admin/dingdanquxiao_quxiaoren',
            },
                    ]
    },
        {
        label:'个人中心',
        to:'',
        children:[
                        {
                label:'修改个人资料',
                to:'/admin/yonghuupdtself',
            },
            {
                label:'留言管理',
                to:'/admin/liuyanban_liuyanren',
            },
                        {
                label:'修改密码',
                to:'/admin/mod',
            },
                        {
                label:'我的收藏',
                to:'/admin/shoucangjilu',
            },
                    ]
    },
    ]
